module.exports = [
  { name: 'NL' },
  { name: 'PE' },
  { name: 'NS' },
  { name: 'NB' },
  { name: 'QC' },
  { name: 'ON' },
  { name: 'MB' },
  { name: 'SK' },
  { name: 'AB' },
  { name: 'BC' },
  { name: 'YT' },
  { name: 'NT' },
  { name: 'NU' },
];
